[postgres]
host = "ep-jolly-wind-ab04u1h2-pooler.eu-west-2.aws.neon.tech" 
port = 5432
database = "neondb"
user = "neondb_owner"
password = "npg_UaRKj0iZof5N" # ¡Pégala aquí entre comillas!
sslmode = "require"
